blank_issues_enabled: false
contact_links:
  - name: "Support tickets"
    url: https://www.edencloud.us/help
    about: "Please favour opening an official ticket if you have an active subscription."
    about: Please use the Transifex tool for Translations (see https://github.com/eden/eden/wiki/Translations for more information).
  - name: "Odoo Help Forums"
    url: https://www.edencloud.us/forum/help
    about: "Please ask and answer questions about custom code, functional aspects or any Odoo-related topic here."
  - name: "Documentation Feedback"
    url: https://github.com/edenapps/documentation/issues
    about: "If your feedback is about the documentation, please post your issue in the dedicated repository."

